source 'http://rubygems.org'

gem "rails", "3.0.3"
gem "warbler" 
gem "jruby-rack", "1.0.0.1" 
gem "haml" 

# Prevent loading of ruby-oci8 gem in JRuby
platforms :ruby do
#  gem 'ruby-oci8', ">= 2.0.4"
end
platforms :jruby do
  gem "glassfish" 
end 

# Use either latest oracle_enhanced adapter version from github
#gem 'activerecord-oracle_enhanced-adapter', '~>1.3.0', :git => 'git://github.com/rsim/oracle-enhanced.git'
# Or use released gem version
gem "activerecord-oracle_enhanced-adapter", "~>1.3.1"

# optionally also use ruby-plsql
gem "ruby-plsql", ">=0.4.3"

group :test, :development do
  platforms :ruby do
    gem "sqlite3-ruby" 
  end
  platforms :jruby do
    gem "activerecord-jdbcsqlite3-adapter"
  end
end
group :test do
  gem "rspec-rails"
  gem "capybara"
  gem "steak" 
end
